<?php

declare(strict_types=1);

namespace LaravelNecromancer\Okf;

/**
 * Builds the static-mostly `README.md` written into every deterministic OKF
 * Knowledge Bundle, so `okf/` is self-explanatory to anyone who finds it by
 * browsing the repository tree, independent of whether they ever read a
 * generated context file that points at it. Only the trailing footer
 * (`$generatedAt`, `$artifactCount`) varies per export — the rest is fixed
 * documentation, mirroring the package README's own OKF section.
 *
 * The mention of `necromancer:okf-enrich` is deliberately static prose, not
 * an existence check against `okf-enriched/` — see ADR 0001: this bundle's
 * own atomic swap only runs when `necromancer:okf` runs, so it has no way
 * to know whether the enriched sibling currently exists.
 */
final class BundleReadmeBuilder
{
    public function build(string $generatedAt, int $artifactCount): string
    {
        $lines = [
            '[//]: # (generated by Laravel Necromancer — do not edit manually)',
            '[//]: # (run `php artisan necromancer:okf` to refresh)',
            '',
            '# OKF Knowledge Bundle',
            '',
            'This directory is a deterministic Open Knowledge Format (OKF) projection of the Necromancer manifest, produced by `php artisan necromancer:okf`. It is read-only, safe to regenerate at any time, and never consulted by Necromancer itself — it never becomes a competing source of truth.',
            '',
            '## Structure',
            '',
            '- `bundle.json` — an index: OKF/schema version, generation timestamp, artifact count, and a content hash used to detect a stale bundle.',
            '- `artifacts/` — one Markdown file per concept, each with authoritative YAML front matter and a concise prose mirror.',
            '',
            '## Concept kinds',
            '',
            '- **Artifact Concepts** — one per collected manifest artifact (routes, models, jobs, and so on).',
            '- **Domain Concepts** and **Flow Concepts** — synthesized for every distinct `domain`/`flow` value declared anywhere in the manifest, linking their member artifacts.',
            '- **ADR Concepts** — copied, with provenance, from every locally declared ADR reference.',
            '',
            "Resolvable cross-artifact relationships (a route's controller, a model's relationships/policy/observers, event/listener pairings) render as Markdown links between concept files; unresolved targets stay plain text.",
            '',
            '## Regenerating',
            '',
            'Run `php artisan necromancer:scan` to refresh the manifest, then `php artisan necromancer:okf` again. Pass `--allow-stale`/`--allow-partial` to export anyway, or `--output=PATH` to write elsewhere.',
            '',
            '## AI-enriched sibling',
            '',
            'An AI-enriched sibling bundle can be generated with `php artisan necromancer:okf-enrich`. It adds a `description` field and an "AI-Enriched Summary" to each concept — it can never change facts, annotations, Artifact IDs, or links — and is written to a separate directory (`okf-enriched/` by default) without ever modifying this one.',
            '',
            '---',
            '',
            '_'.$this->footer($generatedAt, $artifactCount).'_',
        ];

        return implode("\n", $lines);
    }

    private function footer(string $generatedAt, int $artifactCount): string
    {
        $concepts = $artifactCount === 1 ? '1 artifact concept' : "{$artifactCount} artifact concepts";

        return $generatedAt !== ''
            ? "Last generated {$generatedAt} · {$concepts}."
            : "{$concepts}.";
    }
}
