<?php

declare(strict_types=1);

namespace LaravelNecromancer\Inference;

use Illuminate\Support\Str;

final class AdrWriter
{
    public function __construct(private readonly string $outputDir) {}

    /**
     * @param  list<InferredAdr>  $adrs
     * @return list<string>
     */
    public function write(array $adrs, string $date): array
    {
        if (! is_dir($this->outputDir)) {
            mkdir($this->outputDir, 0755, true);
        }

        $existingBySlug = $this->scanExistingBySlug();
        $nextNumber = $this->nextNumber($existingBySlug);
        $written = [];

        foreach ($adrs as $adr) {
            if (isset($existingBySlug[$adr->slug])) {
                [$number, $path] = $existingBySlug[$adr->slug];
            } else {
                $number = $nextNumber++;
                $path = $this->outputDir.'/'.sprintf('%04d', $number).'-'.$adr->slug.'.md';
            }

            file_put_contents($path, $this->render($adr, $number, $date));
            $written[] = $path;
        }

        return $written;
    }

    /**
     * @return array<string, array{0: int, 1: string}>
     */
    private function scanExistingBySlug(): array
    {
        $result = [];

        foreach (glob($this->outputDir.'/[0-9][0-9][0-9][0-9]-*.md') ?: [] as $path) {
            $filename = basename($path, '.md');
            $number = (int) substr($filename, 0, 4);
            $slug = substr($filename, 5);
            $result[$slug] = [$number, $path];
        }

        return $result;
    }

    /** @param array<string, array{0: int, 1: string}> $existingBySlug */
    private function nextNumber(array $existingBySlug): int
    {
        if (empty($existingBySlug)) {
            return 1;
        }

        return max(array_column(array_values($existingBySlug), 0)) + 1;
    }

    private function render(InferredAdr $adr, int $number, string $date): string
    {
        $num = sprintf('%04d', $number);
        $status = Str::ucfirst($adr->status);
        $confidence = Str::ucfirst($adr->confidence);
        $dimension = Str::of($adr->dimension)->replace('-', ' ')->title()->toString();

        return implode("\n", [
            '[//]: # (generated by Laravel Necromancer — do not edit manually)',
            '[//]: # (run `php artisan necromancer:infer` to refresh)',
            '',
            "# ADR {$num}: {$adr->title}",
            '',
            "**Status:** {$status}",
            "**Dimension:** {$dimension}",
            "**Confidence:** {$confidence}",
            "**Date:** {$date}",
            '',
            '## Context',
            '',
            $adr->context,
            '',
            '## Decision',
            '',
            $adr->decision,
            '',
            '## Consequences',
            '',
            $adr->consequences,
            '',
            '## Counter-Evidence',
            '',
            $adr->counter_evidence !== '' ? $adr->counter_evidence : 'No contradicting evidence found in the manifest.',
            '',
        ]);
    }
}
