<?php

declare(strict_types=1);

namespace LaravelNecromancer\Okf\Enrichment;

/**
 * Builds the static-mostly `README.md` written into the enriched sibling
 * bundle, so `okf-enriched/` is self-explanatory on its own — mirroring
 * LaravelNecromancer\Okf\BundleReadmeBuilder for the deterministic bundle,
 * but describing enrichment-specific concerns (what enrichment can and
 * cannot change, caching, privacy, provider/model) instead.
 *
 * The mention of the deterministic `okf/` sibling is deliberately static
 * prose, not an existence check — see ADR 0001: this bundle's own atomic
 * swap only runs when necromancer:okf-enrich runs, so it has no way to
 * know whether the deterministic sibling currently exists.
 */
final class EnrichedBundleReadmeBuilder
{
    public function build(string $generatedAt, int $conceptCount, int $freshCount, int $cachedCount): string
    {
        $lines = [
            '[//]: # (generated by Laravel Necromancer — do not edit manually)',
            '[//]: # (run `php artisan necromancer:okf-enrich` to refresh)',
            '',
            '# AI-Enriched OKF Knowledge Bundle',
            '',
            'This directory is an AI-enriched sibling of the deterministic `okf/` Knowledge Bundle, produced by `php artisan necromancer:okf-enrich`. It is written to its own directory and never modifies the deterministic bundle.',
            '',
            '## What enrichment adds',
            '',
            '- A `description` front-matter field.',
            '- An `## AI-Enriched Summary` body section.',
            '- A `necromancer.enrichment` front-matter block recording the provider, model, prompt version, privacy policy, cache key, and whether the result came from cache — for that specific concept.',
            '',
            '## What enrichment can never change',
            '',
            "Facts, annotations, Artifact IDs, and links stay exactly what the deterministic `okf/` bundle would produce for the same manifest — the AI's output is never given access to those fields, so it has no seam through which it could alter them.",
            '',
            '## Privacy',
            '',
            "The prompt built for each concept excludes raw framework metadata, source file paths and hashes, application configuration, and — for ADR concepts — the ADR's own copied file content. Nothing beyond manifest artifact data (which never contains secrets) is ever sent.",
            '',
            '## Caching',
            '',
            "Each concept is cached independently, keyed by a hash of its own prompt plus provider, model, temperature, and prompt version, so changing one artifact's annotations only invalidates that one concept's cached enrichment. The cache location is `config('necromancer.okf.enrichment.cache')`. Pass `--refresh` to bypass the cache and re-enrich every concept.",
            '',
            '## Configuration',
            '',
            "Provider, model, prompt version, and privacy-policy label default from `config('necromancer.okf.enrichment.provider')`, `.model`, `.prompt_version`, and `.privacy_policy` — override per run with `--provider=`, `--model=`, `--temperature=`, or bypass caching with `--refresh`. The output directory defaults to `config('necromancer.okf.enrichment.output')` (`okf-enriched/`), overridable with `--output=PATH`. `--allow-stale`/`--allow-partial` mirror `necromancer:okf`'s refusal overrides.",
            '',
            '## Deterministic sibling',
            '',
            "The bundle this one enriches is generated with `php artisan necromancer:okf`, written to `config('necromancer.okf.output')` (`okf/` by default).",
            '',
            '---',
            '',
            '_'.$this->footer($generatedAt, $conceptCount, $freshCount, $cachedCount).'_',
        ];

        return implode("\n", $lines);
    }

    private function footer(string $generatedAt, int $conceptCount, int $freshCount, int $cachedCount): string
    {
        $concepts = $conceptCount === 1 ? '1 concept' : "{$conceptCount} concepts";
        $counts = "{$concepts} ({$freshCount} fresh, {$cachedCount} cached)";

        return $generatedAt !== ''
            ? "Last generated {$generatedAt} · {$counts}."
            : "{$counts}.";
    }
}
