<?php

declare(strict_types=1);

use Illuminate\Filesystem\Filesystem;
use LaravelNecromancer\Inference\AdrWriter;
use LaravelNecromancer\Inference\InferredAdr;

function makeAdr(string $title = 'Async Email Delivery', string $slug = 'async-email-delivery', string $status = 'accepted'): InferredAdr
{
    return new InferredAdr(
        title: $title,
        slug: $slug,
        status: $status,
        context: 'Email delivery blocks HTTP responses.',
        decision: 'Use queued jobs on the emails queue.',
        consequences: 'Workers must be running.',
    );
}

beforeEach(function () {
    $this->outputDir = sys_get_temp_dir().'/necromancer-adr-test-'.uniqid();
    mkdir($this->outputDir, 0755, true);
});

afterEach(function () {
    (new Filesystem)->deleteDirectory($this->outputDir);
});

test('write creates the output directory if it does not exist', function () {
    $dir = $this->outputDir.'/adr/necromancer';
    $writer = new AdrWriter($dir);

    $writer->write([makeAdr()], date('Y-m-d'));

    expect(is_dir($dir))->toBeTrue();
});

test('write creates a numbered markdown file', function () {
    $writer = new AdrWriter($this->outputDir);

    $writer->write([makeAdr()], '2026-05-29');

    expect(file_exists($this->outputDir.'/0001-async-email-delivery.md'))->toBeTrue();
});

test('the written file contains the Necromancer header marker', function () {
    $writer = new AdrWriter($this->outputDir);
    $writer->write([makeAdr()], '2026-05-29');

    $content = file_get_contents($this->outputDir.'/0001-async-email-delivery.md');

    expect($content)->toContain('[//]: # (generated by Laravel Necromancer — do not edit manually)');
    expect($content)->toContain('[//]: # (run `php artisan necromancer:infer` to refresh)');
});

test('the written file contains all ADR sections', function () {
    $writer = new AdrWriter($this->outputDir);
    $writer->write([makeAdr()], '2026-05-29');

    $content = file_get_contents($this->outputDir.'/0001-async-email-delivery.md');

    expect($content)->toContain('# ADR 0001: Async Email Delivery');
    expect($content)->toContain('**Status:** Accepted');
    expect($content)->toContain('**Date:** 2026-05-29');
    expect($content)->toContain('**Dimension:** General');
    expect($content)->toContain('**Confidence:** Medium');
    expect($content)->toContain('## Context');
    expect($content)->toContain('Email delivery blocks HTTP responses.');
    expect($content)->toContain('## Decision');
    expect($content)->toContain('Use queued jobs on the emails queue.');
    expect($content)->toContain('## Consequences');
    expect($content)->toContain('Workers must be running.');
});

test('write numbers multiple ADRs sequentially', function () {
    $writer = new AdrWriter($this->outputDir);

    $writer->write([
        makeAdr('Async Email', 'async-email'),
        makeAdr('Policy Auth', 'policy-auth'),
    ], '2026-05-29');

    expect(file_exists($this->outputDir.'/0001-async-email.md'))->toBeTrue();
    expect(file_exists($this->outputDir.'/0002-policy-auth.md'))->toBeTrue();
});

test('write numbers new ADRs starting after existing highest number', function () {
    file_put_contents($this->outputDir.'/0003-existing.md', 'existing');

    $writer = new AdrWriter($this->outputDir);
    $writer->write([makeAdr()], '2026-05-29');

    expect(file_exists($this->outputDir.'/0004-async-email-delivery.md'))->toBeTrue();
});

test('write updates an existing file with the same slug in place', function () {
    file_put_contents($this->outputDir.'/0001-async-email-delivery.md', 'old content');

    $writer = new AdrWriter($this->outputDir);
    $writer->write([makeAdr()], '2026-05-29');

    expect(file_exists($this->outputDir.'/0001-async-email-delivery.md'))->toBeTrue();
    expect(file_exists($this->outputDir.'/0002-async-email-delivery.md'))->toBeFalse();

    $content = file_get_contents($this->outputDir.'/0001-async-email-delivery.md');
    expect($content)->toContain('# ADR 0001: Async Email Delivery');
    expect($content)->not->toContain('old content');
});

test('write returns the list of written file paths', function () {
    $writer = new AdrWriter($this->outputDir);

    $paths = $writer->write([makeAdr()], '2026-05-29');

    expect($paths)->toHaveCount(1);
    expect($paths[0])->toEndWith('0001-async-email-delivery.md');
});

test('the written ADR includes a Counter-Evidence section with provided text', function () {
    $adr = new InferredAdr(
        title: 'Async Email Delivery',
        slug: 'async-email-delivery',
        status: 'accepted',
        context: 'ctx',
        decision: 'dec',
        consequences: 'con',
        counter_evidence: 'No evidence of email volume justifying async delivery.',
    );

    $writer = new AdrWriter($this->outputDir);
    $writer->write([$adr], '2026-06-01');

    $content = file_get_contents($this->outputDir.'/0001-async-email-delivery.md');

    expect($content)
        ->toContain('## Counter-Evidence')
        ->toContain('No evidence of email volume justifying async delivery.');
});

test('the written ADR shows fallback text when counter_evidence is empty', function () {
    $writer = new AdrWriter($this->outputDir);
    $writer->write([makeAdr()], '2026-06-01');

    $content = file_get_contents($this->outputDir.'/0001-async-email-delivery.md');

    expect($content)
        ->toContain('## Counter-Evidence')
        ->toContain('No contradicting evidence found in the manifest.');
});
